spring:
    liquibase:
        enabled: true
        change-log: classpath:config/liquibase/master.xml

    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
            driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
            jdbc-url: jdbc:log4jdbc:mysql://localhost:3377/slipping?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
            username: slipp
            password: slipppw
            poolName: Hikari
            maximum-pool-size: 3
            minimum-idle: 3
            max-lifetime: 57600
            connection-timeout: 57600
            idle-timeout: 30000
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true

mybatis:
    #    type-aliases-package: com.example.domain.model
    #    type-handlers-package: com.example.typehandler
    configuration:
        map-underscore-to-camel-case: true
        default-fetch-size: 100
        default-statement-timeout: 30

logging:
    level:
        net.slipp: DEBUG
        org.mybatis: info
